# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ConfigClientPosition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cid': 'str',
        'lat': 'float',
        'lng': 'float',
        'uid': 'str',
        'utc': 'str'
    }

    attribute_map = {
        'cid': 'cid',
        'lat': 'lat',
        'lng': 'lng',
        'uid': 'uid',
        'utc': 'utc'
    }

    def __init__(self, cid=None, lat=None, lng=None, uid=None, utc=None, _configuration=None):  # noqa: E501
        """ConfigClientPosition - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._cid = None
        self._lat = None
        self._lng = None
        self._uid = None
        self._utc = None
        self.discriminator = None

        if cid is not None:
            self.cid = cid
        if lat is not None:
            self.lat = lat
        if lng is not None:
            self.lng = lng
        if uid is not None:
            self.uid = uid
        if utc is not None:
            self.utc = utc

    @property
    def cid(self):
        """Gets the cid of this ConfigClientPosition.  # noqa: E501


        :return: The cid of this ConfigClientPosition.  # noqa: E501
        :rtype: str
        """
        return self._cid

    @cid.setter
    def cid(self, cid):
        """Sets the cid of this ConfigClientPosition.


        :param cid: The cid of this ConfigClientPosition.  # noqa: E501
        :type: str
        """

        self._cid = cid

    @property
    def lat(self):
        """Gets the lat of this ConfigClientPosition.  # noqa: E501


        :return: The lat of this ConfigClientPosition.  # noqa: E501
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """Sets the lat of this ConfigClientPosition.


        :param lat: The lat of this ConfigClientPosition.  # noqa: E501
        :type: float
        """

        self._lat = lat

    @property
    def lng(self):
        """Gets the lng of this ConfigClientPosition.  # noqa: E501


        :return: The lng of this ConfigClientPosition.  # noqa: E501
        :rtype: float
        """
        return self._lng

    @lng.setter
    def lng(self, lng):
        """Sets the lng of this ConfigClientPosition.


        :param lng: The lng of this ConfigClientPosition.  # noqa: E501
        :type: float
        """

        self._lng = lng

    @property
    def uid(self):
        """Gets the uid of this ConfigClientPosition.  # noqa: E501


        :return: The uid of this ConfigClientPosition.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this ConfigClientPosition.


        :param uid: The uid of this ConfigClientPosition.  # noqa: E501
        :type: str
        """

        self._uid = uid

    @property
    def utc(self):
        """Gets the utc of this ConfigClientPosition.  # noqa: E501


        :return: The utc of this ConfigClientPosition.  # noqa: E501
        :rtype: str
        """
        return self._utc

    @utc.setter
    def utc(self, utc):
        """Sets the utc of this ConfigClientPosition.


        :param utc: The utc of this ConfigClientPosition.  # noqa: E501
        :type: str
        """

        self._utc = utc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigClientPosition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigClientPosition):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConfigClientPosition):
            return True

        return self.to_dict() != other.to_dict()
