# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class EntityPhotoLabel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'label': 'EntityLabel',
        'label_id': 'int',
        'label_src': 'str',
        'photo': 'EntityPhoto',
        'photo_id': 'int',
        'uncertainty': 'int'
    }

    attribute_map = {
        'label': 'label',
        'label_id': 'labelID',
        'label_src': 'labelSrc',
        'photo': 'photo',
        'photo_id': 'photoID',
        'uncertainty': 'uncertainty'
    }

    def __init__(self, label=None, label_id=None, label_src=None, photo=None, photo_id=None, uncertainty=None, _configuration=None):  # noqa: E501
        """EntityPhotoLabel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._label = None
        self._label_id = None
        self._label_src = None
        self._photo = None
        self._photo_id = None
        self._uncertainty = None
        self.discriminator = None

        if label is not None:
            self.label = label
        if label_id is not None:
            self.label_id = label_id
        if label_src is not None:
            self.label_src = label_src
        if photo is not None:
            self.photo = photo
        if photo_id is not None:
            self.photo_id = photo_id
        if uncertainty is not None:
            self.uncertainty = uncertainty

    @property
    def label(self):
        """Gets the label of this EntityPhotoLabel.  # noqa: E501


        :return: The label of this EntityPhotoLabel.  # noqa: E501
        :rtype: EntityLabel
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this EntityPhotoLabel.


        :param label: The label of this EntityPhotoLabel.  # noqa: E501
        :type: EntityLabel
        """

        self._label = label

    @property
    def label_id(self):
        """Gets the label_id of this EntityPhotoLabel.  # noqa: E501


        :return: The label_id of this EntityPhotoLabel.  # noqa: E501
        :rtype: int
        """
        return self._label_id

    @label_id.setter
    def label_id(self, label_id):
        """Sets the label_id of this EntityPhotoLabel.


        :param label_id: The label_id of this EntityPhotoLabel.  # noqa: E501
        :type: int
        """

        self._label_id = label_id

    @property
    def label_src(self):
        """Gets the label_src of this EntityPhotoLabel.  # noqa: E501


        :return: The label_src of this EntityPhotoLabel.  # noqa: E501
        :rtype: str
        """
        return self._label_src

    @label_src.setter
    def label_src(self, label_src):
        """Sets the label_src of this EntityPhotoLabel.


        :param label_src: The label_src of this EntityPhotoLabel.  # noqa: E501
        :type: str
        """

        self._label_src = label_src

    @property
    def photo(self):
        """Gets the photo of this EntityPhotoLabel.  # noqa: E501


        :return: The photo of this EntityPhotoLabel.  # noqa: E501
        :rtype: EntityPhoto
        """
        return self._photo

    @photo.setter
    def photo(self, photo):
        """Sets the photo of this EntityPhotoLabel.


        :param photo: The photo of this EntityPhotoLabel.  # noqa: E501
        :type: EntityPhoto
        """

        self._photo = photo

    @property
    def photo_id(self):
        """Gets the photo_id of this EntityPhotoLabel.  # noqa: E501


        :return: The photo_id of this EntityPhotoLabel.  # noqa: E501
        :rtype: int
        """
        return self._photo_id

    @photo_id.setter
    def photo_id(self, photo_id):
        """Sets the photo_id of this EntityPhotoLabel.


        :param photo_id: The photo_id of this EntityPhotoLabel.  # noqa: E501
        :type: int
        """

        self._photo_id = photo_id

    @property
    def uncertainty(self):
        """Gets the uncertainty of this EntityPhotoLabel.  # noqa: E501


        :return: The uncertainty of this EntityPhotoLabel.  # noqa: E501
        :rtype: int
        """
        return self._uncertainty

    @uncertainty.setter
    def uncertainty(self, uncertainty):
        """Sets the uncertainty of this EntityPhotoLabel.


        :param uncertainty: The uncertainty of this EntityPhotoLabel.  # noqa: E501
        :type: int
        """

        self._uncertainty = uncertainty

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EntityPhotoLabel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EntityPhotoLabel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EntityPhotoLabel):
            return True

        return self.to_dict() != other.to_dict()
