# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class EnvResourcesMemory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'free': 'int',
        'info': 'str',
        'reserved': 'int',
        'total': 'int',
        'used': 'int'
    }

    attribute_map = {
        'free': 'free',
        'info': 'info',
        'reserved': 'reserved',
        'total': 'total',
        'used': 'used'
    }

    def __init__(self, free=None, info=None, reserved=None, total=None, used=None, _configuration=None):  # noqa: E501
        """EnvResourcesMemory - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._free = None
        self._info = None
        self._reserved = None
        self._total = None
        self._used = None
        self.discriminator = None

        if free is not None:
            self.free = free
        if info is not None:
            self.info = info
        if reserved is not None:
            self.reserved = reserved
        if total is not None:
            self.total = total
        if used is not None:
            self.used = used

    @property
    def free(self):
        """Gets the free of this EnvResourcesMemory.  # noqa: E501


        :return: The free of this EnvResourcesMemory.  # noqa: E501
        :rtype: int
        """
        return self._free

    @free.setter
    def free(self, free):
        """Sets the free of this EnvResourcesMemory.


        :param free: The free of this EnvResourcesMemory.  # noqa: E501
        :type: int
        """

        self._free = free

    @property
    def info(self):
        """Gets the info of this EnvResourcesMemory.  # noqa: E501


        :return: The info of this EnvResourcesMemory.  # noqa: E501
        :rtype: str
        """
        return self._info

    @info.setter
    def info(self, info):
        """Sets the info of this EnvResourcesMemory.


        :param info: The info of this EnvResourcesMemory.  # noqa: E501
        :type: str
        """

        self._info = info

    @property
    def reserved(self):
        """Gets the reserved of this EnvResourcesMemory.  # noqa: E501


        :return: The reserved of this EnvResourcesMemory.  # noqa: E501
        :rtype: int
        """
        return self._reserved

    @reserved.setter
    def reserved(self, reserved):
        """Sets the reserved of this EnvResourcesMemory.


        :param reserved: The reserved of this EnvResourcesMemory.  # noqa: E501
        :type: int
        """

        self._reserved = reserved

    @property
    def total(self):
        """Gets the total of this EnvResourcesMemory.  # noqa: E501


        :return: The total of this EnvResourcesMemory.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this EnvResourcesMemory.


        :param total: The total of this EnvResourcesMemory.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def used(self):
        """Gets the used of this EnvResourcesMemory.  # noqa: E501


        :return: The used of this EnvResourcesMemory.  # noqa: E501
        :rtype: int
        """
        return self._used

    @used.setter
    def used(self, used):
        """Sets the used of this EnvResourcesMemory.


        :param used: The used of this EnvResourcesMemory.  # noqa: E501
        :type: int
        """

        self._used = used

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnvResourcesMemory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnvResourcesMemory):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EnvResourcesMemory):
            return True

        return self.to_dict() != other.to_dict()
