# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SearchSubject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alias': 'str',
        'excluded': 'bool',
        'favorite': 'bool',
        'file_count': 'int',
        'hidden': 'bool',
        'marker_src': 'str',
        'marker_uid': 'str',
        'name': 'str',
        'photo_count': 'int',
        'private': 'bool',
        'slug': 'str',
        'thumb': 'str',
        'thumb_src': 'str',
        'type': 'str',
        'uid': 'str'
    }

    attribute_map = {
        'alias': 'Alias',
        'excluded': 'Excluded',
        'favorite': 'Favorite',
        'file_count': 'FileCount',
        'hidden': 'Hidden',
        'marker_src': 'MarkerSrc',
        'marker_uid': 'MarkerUID',
        'name': 'Name',
        'photo_count': 'PhotoCount',
        'private': 'Private',
        'slug': 'Slug',
        'thumb': 'Thumb',
        'thumb_src': 'ThumbSrc',
        'type': 'Type',
        'uid': 'UID'
    }

    def __init__(self, alias=None, excluded=None, favorite=None, file_count=None, hidden=None, marker_src=None, marker_uid=None, name=None, photo_count=None, private=None, slug=None, thumb=None, thumb_src=None, type=None, uid=None, _configuration=None):  # noqa: E501
        """SearchSubject - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._alias = None
        self._excluded = None
        self._favorite = None
        self._file_count = None
        self._hidden = None
        self._marker_src = None
        self._marker_uid = None
        self._name = None
        self._photo_count = None
        self._private = None
        self._slug = None
        self._thumb = None
        self._thumb_src = None
        self._type = None
        self._uid = None
        self.discriminator = None

        if alias is not None:
            self.alias = alias
        if excluded is not None:
            self.excluded = excluded
        if favorite is not None:
            self.favorite = favorite
        if file_count is not None:
            self.file_count = file_count
        if hidden is not None:
            self.hidden = hidden
        if marker_src is not None:
            self.marker_src = marker_src
        if marker_uid is not None:
            self.marker_uid = marker_uid
        if name is not None:
            self.name = name
        if photo_count is not None:
            self.photo_count = photo_count
        if private is not None:
            self.private = private
        if slug is not None:
            self.slug = slug
        if thumb is not None:
            self.thumb = thumb
        if thumb_src is not None:
            self.thumb_src = thumb_src
        if type is not None:
            self.type = type
        if uid is not None:
            self.uid = uid

    @property
    def alias(self):
        """Gets the alias of this SearchSubject.  # noqa: E501


        :return: The alias of this SearchSubject.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this SearchSubject.


        :param alias: The alias of this SearchSubject.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def excluded(self):
        """Gets the excluded of this SearchSubject.  # noqa: E501


        :return: The excluded of this SearchSubject.  # noqa: E501
        :rtype: bool
        """
        return self._excluded

    @excluded.setter
    def excluded(self, excluded):
        """Sets the excluded of this SearchSubject.


        :param excluded: The excluded of this SearchSubject.  # noqa: E501
        :type: bool
        """

        self._excluded = excluded

    @property
    def favorite(self):
        """Gets the favorite of this SearchSubject.  # noqa: E501


        :return: The favorite of this SearchSubject.  # noqa: E501
        :rtype: bool
        """
        return self._favorite

    @favorite.setter
    def favorite(self, favorite):
        """Sets the favorite of this SearchSubject.


        :param favorite: The favorite of this SearchSubject.  # noqa: E501
        :type: bool
        """

        self._favorite = favorite

    @property
    def file_count(self):
        """Gets the file_count of this SearchSubject.  # noqa: E501


        :return: The file_count of this SearchSubject.  # noqa: E501
        :rtype: int
        """
        return self._file_count

    @file_count.setter
    def file_count(self, file_count):
        """Sets the file_count of this SearchSubject.


        :param file_count: The file_count of this SearchSubject.  # noqa: E501
        :type: int
        """

        self._file_count = file_count

    @property
    def hidden(self):
        """Gets the hidden of this SearchSubject.  # noqa: E501


        :return: The hidden of this SearchSubject.  # noqa: E501
        :rtype: bool
        """
        return self._hidden

    @hidden.setter
    def hidden(self, hidden):
        """Sets the hidden of this SearchSubject.


        :param hidden: The hidden of this SearchSubject.  # noqa: E501
        :type: bool
        """

        self._hidden = hidden

    @property
    def marker_src(self):
        """Gets the marker_src of this SearchSubject.  # noqa: E501


        :return: The marker_src of this SearchSubject.  # noqa: E501
        :rtype: str
        """
        return self._marker_src

    @marker_src.setter
    def marker_src(self, marker_src):
        """Sets the marker_src of this SearchSubject.


        :param marker_src: The marker_src of this SearchSubject.  # noqa: E501
        :type: str
        """

        self._marker_src = marker_src

    @property
    def marker_uid(self):
        """Gets the marker_uid of this SearchSubject.  # noqa: E501


        :return: The marker_uid of this SearchSubject.  # noqa: E501
        :rtype: str
        """
        return self._marker_uid

    @marker_uid.setter
    def marker_uid(self, marker_uid):
        """Sets the marker_uid of this SearchSubject.


        :param marker_uid: The marker_uid of this SearchSubject.  # noqa: E501
        :type: str
        """

        self._marker_uid = marker_uid

    @property
    def name(self):
        """Gets the name of this SearchSubject.  # noqa: E501


        :return: The name of this SearchSubject.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SearchSubject.


        :param name: The name of this SearchSubject.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def photo_count(self):
        """Gets the photo_count of this SearchSubject.  # noqa: E501


        :return: The photo_count of this SearchSubject.  # noqa: E501
        :rtype: int
        """
        return self._photo_count

    @photo_count.setter
    def photo_count(self, photo_count):
        """Sets the photo_count of this SearchSubject.


        :param photo_count: The photo_count of this SearchSubject.  # noqa: E501
        :type: int
        """

        self._photo_count = photo_count

    @property
    def private(self):
        """Gets the private of this SearchSubject.  # noqa: E501


        :return: The private of this SearchSubject.  # noqa: E501
        :rtype: bool
        """
        return self._private

    @private.setter
    def private(self, private):
        """Sets the private of this SearchSubject.


        :param private: The private of this SearchSubject.  # noqa: E501
        :type: bool
        """

        self._private = private

    @property
    def slug(self):
        """Gets the slug of this SearchSubject.  # noqa: E501


        :return: The slug of this SearchSubject.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this SearchSubject.


        :param slug: The slug of this SearchSubject.  # noqa: E501
        :type: str
        """

        self._slug = slug

    @property
    def thumb(self):
        """Gets the thumb of this SearchSubject.  # noqa: E501


        :return: The thumb of this SearchSubject.  # noqa: E501
        :rtype: str
        """
        return self._thumb

    @thumb.setter
    def thumb(self, thumb):
        """Sets the thumb of this SearchSubject.


        :param thumb: The thumb of this SearchSubject.  # noqa: E501
        :type: str
        """

        self._thumb = thumb

    @property
    def thumb_src(self):
        """Gets the thumb_src of this SearchSubject.  # noqa: E501


        :return: The thumb_src of this SearchSubject.  # noqa: E501
        :rtype: str
        """
        return self._thumb_src

    @thumb_src.setter
    def thumb_src(self, thumb_src):
        """Sets the thumb_src of this SearchSubject.


        :param thumb_src: The thumb_src of this SearchSubject.  # noqa: E501
        :type: str
        """

        self._thumb_src = thumb_src

    @property
    def type(self):
        """Gets the type of this SearchSubject.  # noqa: E501


        :return: The type of this SearchSubject.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SearchSubject.


        :param type: The type of this SearchSubject.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def uid(self):
        """Gets the uid of this SearchSubject.  # noqa: E501


        :return: The uid of this SearchSubject.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this SearchSubject.


        :param uid: The uid of this SearchSubject.  # noqa: E501
        :type: str
        """

        self._uid = uid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchSubject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchSubject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SearchSubject):
            return True

        return self.to_dict() != other.to_dict()
