# coding: utf-8

"""
    PhotoPrism API

    API request bodies and responses are usually JSON-encoded, except for binary data and some of the OAuth2 endpoints. Note that the `Content-Type` header must be set to `application/json` for this, as the request may otherwise fail with error 400. When clients have a valid access token, e.g. obtained through the `POST /api/v1/session` or `POST /api/v1/oauth/token` endpoint, they can use a standard Bearer Authorization header to authenticate their requests. Submitting the access token with a custom `X-Auth-Token` header is supported as well.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SearchFace(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'collision_radius': 'float',
        'collisions': 'int',
        'created_at': 'str',
        'face_dist': 'float',
        'file_uid': 'str',
        'hidden': 'bool',
        'id': 'str',
        'invalid': 'bool',
        'marker_uid': 'str',
        'matched_at': 'str',
        'name': 'str',
        'review': 'bool',
        'sample_radius': 'float',
        'samples': 'int',
        'score': 'int',
        'size': 'int',
        'src': 'str',
        'subj_src': 'str',
        'subj_uid': 'str',
        'thumb': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'collision_radius': 'CollisionRadius',
        'collisions': 'Collisions',
        'created_at': 'CreatedAt',
        'face_dist': 'FaceDist',
        'file_uid': 'FileUID',
        'hidden': 'Hidden',
        'id': 'ID',
        'invalid': 'Invalid',
        'marker_uid': 'MarkerUID',
        'matched_at': 'MatchedAt',
        'name': 'Name',
        'review': 'Review',
        'sample_radius': 'SampleRadius',
        'samples': 'Samples',
        'score': 'Score',
        'size': 'Size',
        'src': 'Src',
        'subj_src': 'SubjSrc',
        'subj_uid': 'SubjUID',
        'thumb': 'Thumb',
        'updated_at': 'UpdatedAt'
    }

    def __init__(self, collision_radius=None, collisions=None, created_at=None, face_dist=None, file_uid=None, hidden=None, id=None, invalid=None, marker_uid=None, matched_at=None, name=None, review=None, sample_radius=None, samples=None, score=None, size=None, src=None, subj_src=None, subj_uid=None, thumb=None, updated_at=None, _configuration=None):  # noqa: E501
        """SearchFace - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._collision_radius = None
        self._collisions = None
        self._created_at = None
        self._face_dist = None
        self._file_uid = None
        self._hidden = None
        self._id = None
        self._invalid = None
        self._marker_uid = None
        self._matched_at = None
        self._name = None
        self._review = None
        self._sample_radius = None
        self._samples = None
        self._score = None
        self._size = None
        self._src = None
        self._subj_src = None
        self._subj_uid = None
        self._thumb = None
        self._updated_at = None
        self.discriminator = None

        if collision_radius is not None:
            self.collision_radius = collision_radius
        if collisions is not None:
            self.collisions = collisions
        if created_at is not None:
            self.created_at = created_at
        if face_dist is not None:
            self.face_dist = face_dist
        if file_uid is not None:
            self.file_uid = file_uid
        if hidden is not None:
            self.hidden = hidden
        if id is not None:
            self.id = id
        if invalid is not None:
            self.invalid = invalid
        if marker_uid is not None:
            self.marker_uid = marker_uid
        if matched_at is not None:
            self.matched_at = matched_at
        if name is not None:
            self.name = name
        if review is not None:
            self.review = review
        if sample_radius is not None:
            self.sample_radius = sample_radius
        if samples is not None:
            self.samples = samples
        if score is not None:
            self.score = score
        if size is not None:
            self.size = size
        if src is not None:
            self.src = src
        if subj_src is not None:
            self.subj_src = subj_src
        if subj_uid is not None:
            self.subj_uid = subj_uid
        if thumb is not None:
            self.thumb = thumb
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def collision_radius(self):
        """Gets the collision_radius of this SearchFace.  # noqa: E501


        :return: The collision_radius of this SearchFace.  # noqa: E501
        :rtype: float
        """
        return self._collision_radius

    @collision_radius.setter
    def collision_radius(self, collision_radius):
        """Sets the collision_radius of this SearchFace.


        :param collision_radius: The collision_radius of this SearchFace.  # noqa: E501
        :type: float
        """

        self._collision_radius = collision_radius

    @property
    def collisions(self):
        """Gets the collisions of this SearchFace.  # noqa: E501


        :return: The collisions of this SearchFace.  # noqa: E501
        :rtype: int
        """
        return self._collisions

    @collisions.setter
    def collisions(self, collisions):
        """Sets the collisions of this SearchFace.


        :param collisions: The collisions of this SearchFace.  # noqa: E501
        :type: int
        """

        self._collisions = collisions

    @property
    def created_at(self):
        """Gets the created_at of this SearchFace.  # noqa: E501


        :return: The created_at of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this SearchFace.


        :param created_at: The created_at of this SearchFace.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def face_dist(self):
        """Gets the face_dist of this SearchFace.  # noqa: E501


        :return: The face_dist of this SearchFace.  # noqa: E501
        :rtype: float
        """
        return self._face_dist

    @face_dist.setter
    def face_dist(self, face_dist):
        """Sets the face_dist of this SearchFace.


        :param face_dist: The face_dist of this SearchFace.  # noqa: E501
        :type: float
        """

        self._face_dist = face_dist

    @property
    def file_uid(self):
        """Gets the file_uid of this SearchFace.  # noqa: E501


        :return: The file_uid of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._file_uid

    @file_uid.setter
    def file_uid(self, file_uid):
        """Sets the file_uid of this SearchFace.


        :param file_uid: The file_uid of this SearchFace.  # noqa: E501
        :type: str
        """

        self._file_uid = file_uid

    @property
    def hidden(self):
        """Gets the hidden of this SearchFace.  # noqa: E501


        :return: The hidden of this SearchFace.  # noqa: E501
        :rtype: bool
        """
        return self._hidden

    @hidden.setter
    def hidden(self, hidden):
        """Sets the hidden of this SearchFace.


        :param hidden: The hidden of this SearchFace.  # noqa: E501
        :type: bool
        """

        self._hidden = hidden

    @property
    def id(self):
        """Gets the id of this SearchFace.  # noqa: E501


        :return: The id of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SearchFace.


        :param id: The id of this SearchFace.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def invalid(self):
        """Gets the invalid of this SearchFace.  # noqa: E501


        :return: The invalid of this SearchFace.  # noqa: E501
        :rtype: bool
        """
        return self._invalid

    @invalid.setter
    def invalid(self, invalid):
        """Sets the invalid of this SearchFace.


        :param invalid: The invalid of this SearchFace.  # noqa: E501
        :type: bool
        """

        self._invalid = invalid

    @property
    def marker_uid(self):
        """Gets the marker_uid of this SearchFace.  # noqa: E501


        :return: The marker_uid of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._marker_uid

    @marker_uid.setter
    def marker_uid(self, marker_uid):
        """Sets the marker_uid of this SearchFace.


        :param marker_uid: The marker_uid of this SearchFace.  # noqa: E501
        :type: str
        """

        self._marker_uid = marker_uid

    @property
    def matched_at(self):
        """Gets the matched_at of this SearchFace.  # noqa: E501


        :return: The matched_at of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._matched_at

    @matched_at.setter
    def matched_at(self, matched_at):
        """Sets the matched_at of this SearchFace.


        :param matched_at: The matched_at of this SearchFace.  # noqa: E501
        :type: str
        """

        self._matched_at = matched_at

    @property
    def name(self):
        """Gets the name of this SearchFace.  # noqa: E501


        :return: The name of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SearchFace.


        :param name: The name of this SearchFace.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def review(self):
        """Gets the review of this SearchFace.  # noqa: E501


        :return: The review of this SearchFace.  # noqa: E501
        :rtype: bool
        """
        return self._review

    @review.setter
    def review(self, review):
        """Sets the review of this SearchFace.


        :param review: The review of this SearchFace.  # noqa: E501
        :type: bool
        """

        self._review = review

    @property
    def sample_radius(self):
        """Gets the sample_radius of this SearchFace.  # noqa: E501


        :return: The sample_radius of this SearchFace.  # noqa: E501
        :rtype: float
        """
        return self._sample_radius

    @sample_radius.setter
    def sample_radius(self, sample_radius):
        """Sets the sample_radius of this SearchFace.


        :param sample_radius: The sample_radius of this SearchFace.  # noqa: E501
        :type: float
        """

        self._sample_radius = sample_radius

    @property
    def samples(self):
        """Gets the samples of this SearchFace.  # noqa: E501


        :return: The samples of this SearchFace.  # noqa: E501
        :rtype: int
        """
        return self._samples

    @samples.setter
    def samples(self, samples):
        """Sets the samples of this SearchFace.


        :param samples: The samples of this SearchFace.  # noqa: E501
        :type: int
        """

        self._samples = samples

    @property
    def score(self):
        """Gets the score of this SearchFace.  # noqa: E501


        :return: The score of this SearchFace.  # noqa: E501
        :rtype: int
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this SearchFace.


        :param score: The score of this SearchFace.  # noqa: E501
        :type: int
        """

        self._score = score

    @property
    def size(self):
        """Gets the size of this SearchFace.  # noqa: E501


        :return: The size of this SearchFace.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this SearchFace.


        :param size: The size of this SearchFace.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def src(self):
        """Gets the src of this SearchFace.  # noqa: E501


        :return: The src of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._src

    @src.setter
    def src(self, src):
        """Sets the src of this SearchFace.


        :param src: The src of this SearchFace.  # noqa: E501
        :type: str
        """

        self._src = src

    @property
    def subj_src(self):
        """Gets the subj_src of this SearchFace.  # noqa: E501


        :return: The subj_src of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._subj_src

    @subj_src.setter
    def subj_src(self, subj_src):
        """Sets the subj_src of this SearchFace.


        :param subj_src: The subj_src of this SearchFace.  # noqa: E501
        :type: str
        """

        self._subj_src = subj_src

    @property
    def subj_uid(self):
        """Gets the subj_uid of this SearchFace.  # noqa: E501


        :return: The subj_uid of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._subj_uid

    @subj_uid.setter
    def subj_uid(self, subj_uid):
        """Sets the subj_uid of this SearchFace.


        :param subj_uid: The subj_uid of this SearchFace.  # noqa: E501
        :type: str
        """

        self._subj_uid = subj_uid

    @property
    def thumb(self):
        """Gets the thumb of this SearchFace.  # noqa: E501


        :return: The thumb of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._thumb

    @thumb.setter
    def thumb(self, thumb):
        """Sets the thumb of this SearchFace.


        :param thumb: The thumb of this SearchFace.  # noqa: E501
        :type: str
        """

        self._thumb = thumb

    @property
    def updated_at(self):
        """Gets the updated_at of this SearchFace.  # noqa: E501


        :return: The updated_at of this SearchFace.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this SearchFace.


        :param updated_at: The updated_at of this SearchFace.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchFace, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchFace):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SearchFace):
            return True

        return self.to_dict() != other.to_dict()
